### ISSUE TITLE
Allow Remote Plex Server

### ISSUE THREAD

**Issue by markburgessstl** [gloaysa/whatsplaying#1]
This is really great, but I'd really like to be able to run on a machine other than my actual Plex server.  Can you add a config option to enter the Plex server URL, instead of assuming it's the same machine?  Thank you for your consideration.

**Comment by gloaysa** [comment]
What problem are problems are you getting?

The app is not meant to be run (although is possible) in the same machine as your plex server. I use it on my iPad, for example.

The way it works is that I use the token to log you in on `https://plex.tv/api/v2/resources`. I really didn't want to use the internet for anything on this project to have everything working even if you don't have internet connection, but haven't found a reliable way of doing so (yet).

If you could post here the logs of the app in case you are having errors I'll be able to help you.

**Comment by markburgessstl** [comment]
No sure she the logs are, but here is my browser console output:

[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=0&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=0&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=2&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=3&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=4&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=5&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=6&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=7&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=8&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
> Selected Element
< <html lang="en">…</html>
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=9&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=10&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=11&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=12&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=13&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=14&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=15&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=16&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=17&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=18&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=19&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=20&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=21&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=22&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=23&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=24&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=25&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=26&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=27&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=28&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=29&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=30&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=31&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=32&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=33&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=34&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=35&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=36&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=37&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=38&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=39&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=40&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=41&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=42&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=43&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=44&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=45&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=46&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=47&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=48&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=49&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=50&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=51&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=52&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=53&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Failed to load resource: The request timed out. (resources, line 0)
[Error] Failed to load resource: The request timed out. (resources, line 0)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=54&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=55&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=56&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=57&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=58&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=59&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=60&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=61&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=62&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=63&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=64&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=65&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=66&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=67&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=68&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=69&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=70&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=71&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=72&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=73&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=74&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.
[Error] Fetch API cannot load http://192.168.0.7:32500/player/timeline/poll?commandID=75&includeMetadata=1&type=music due to access control checks.
[Error] Failed to load resource: Could not connect to the server. (poll, line 0)
[Error] Error updating state – TypeError: Load failed
TypeError: Load failed
	(anonymous function) (bundle.js:1375)
[Error] Could not connect to the server.

**Comment by gloaysa** [comment]
is your server outside of the local network? I think I know what the problem could be, but please confirm this.

**Comment by markburgessstl** [comment]
They are both on the same network.  My desktop is 192.168.0.7 and my server is 192.168.0.2

**Comment by gloaysa** [comment]
The `poll` request is actually to poll your device, so .7 is the right one.

I was able to reproduce your issue. Please, go to Plexamp in your desktop and Settings/Device/Remote Control and activate Remote Control.

You might have to close Plexamp and open it again.

Let me know if this is solves your issue, I will update the README to include this info.

**Comment by markburgessstl** [comment]
That worked!  Thank you.

**Comment by gloaysa** [comment]
Great! I'm working on adding meaningful error messages to the users, so your input was really valuable. I will add prompting the user to check that they have this setting correctly set.

Enjoy the app!
