### ISSUE TITLE
[Request] Add blur to background to fill screen

### ISSUE THREAD

**Issue by lukemattle** [gloaysa/whatsplaying#4]
It would be great to have something to fill the blank space,
![Screenshot 2024-03-21 180400](https://github.com/gloaysa/whatsplaying/assets/84141955/a761efd4-af22-435b-ad16-7cd3a4930b57)
something similar to Plexamp's ultrablur background would be cool
![Screenshot 2024-03-21 180417](https://github.com/gloaysa/whatsplaying/assets/84141955/90377e5e-198f-4adc-914d-52a62fc511e9)

**Comment by gloaysa** [comment]
You mean instead of the black background? I put it black so it would be as less invasive as possible, but could add as a configuration different backgrounds, good idea!

Adding it to the backlog, will leave the ticket open until it’s implemented.

**Comment by lukemattle** [comment]
Great thanks
