### ISSUE TITLE
[Bug] Lyrics are consistently a little ahead

### ISSUE THREAD

**Issue by lukemattle** [gloaysa/whatsplaying#6]
In songs which have synced lyrics, the highlighted lyric is always a couple of seconds ahead of the actual lyric. Lyrics on the Web UI and Plexamp are correctly synced.
NB: I only use the lyrics Plex pulls from LyricFind

**Comment by gloaysa** [comment]
ahead? I had the opposite problems (a second or so behind). I've been working hard on this, but I think there a few things into play here that are out of my control:
 - Latency with the server (something that could explain yours being ahead is if you are running the app in the same machine as your plex server is).
 - Latency with speaker (if you are playing over wifi/bluetooth speakers). In this case, I have even seen Plexamp get out of sync sometimes (in songs that are perfectly timed when playing directly connected to my headphones).
 - Obviously badly timed lyrics (not talking about your specific case, but it does happen).
 - The app is piggybacking on Plexamp, meaning that what it actually knows at the ms what's playing, is Plexamp. I get the info from the server.

My working solution (in paper) is to add control to adjust the sync. It's not perfect and you might have to adjust it again if the conditions changes (latency, bad timed lyrics...).

As an user, I'd like your feedback about this idea.

**Comment by lukemattle** [comment]
You are correct, I am running the app on the same machine as my Plex server. I do cast from Plexamp --> Plexamp but I tested the lyric sync with Plex's web UI and it was out of sync by the same amount (to my eyes at least), so I think that specific casting method has minimal latency.
Given your explanation, I think your solution is perfect as anything else would require the delay to be the same for everyone.

It may be beneficial to have the sync control on the same page as the lyrics so that you don't have to go back and forth between the config page and the main page to get the sync correct.
