### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by psybernoid** [gloaysa/whatsplaying#7]
Is there any chance to add environment variables to the docker image?

For example, defining the PLEX_TOKEN in my compose would be a lot more convenient than having to define it in the browser.

**Comment by gloaysa** [comment]
This is not possible today and I'd need to think about it.

The original idea is to have a 1 per device instance (the configuration is stored in the browser's session storage). The idea being that you could have more than one client with different configurations. The token determines the user. So if you want to have one client displaying what you are playing and then another instance displaying what other person is playing, you could do so.

Maybe allow a general configuration that could be overridden locally is a good compromise?

**Comment by psybernoid** [comment]
Maybe, yes.

I'll outline my use-case a little. I have 2 Raspberry Pi 4's, each with a screen attached and Plexamp headless installed. They currently boot up and launch a kiosk chrome browser - broad details on that [here](https://dietpi.com/docs/software/desktop/#chromium) the browser is set to open a page hosted on my internal network, which, long story short, contains a list of iframe links. So small thumbnails on the left and the target site opens in an iframe on the main part of the display. Currently, the plex link opens up 127.0.0.1:32500, which will of course, display the locally running Plexamp instance.

I could, quite easily have whatisplaying running via docker (assuming you've released an arm64 image) and point that link to 127.0.0.1:5000

However, the issue is, that every now & then, the chromium browser on these things likes to forget its cookies, and they don't have a keyboard attached. The kiosk browser doesn't present a touch keyboard either (due to the fact it's not running an actual DE)

Being able to define the token in the environment variables would neatly sidestep that problem
